from ytmusicapi.navigation import *

def parse_menu_playlists(data, result) -> None: ...
def get_item_text(item, index, run_index: int = ..., none_if_absent: bool = ...): ...
def get_flex_column_item(item, index): ...
def get_fixed_column_item(item, index): ...
def get_browse_id(item, index): ...
def get_dot_separator_index(runs): ...
def parse_duration(duration): ...
def i18n(method): ...
