from ytmusicapi.parsers.browsing import *
from _typeshed import Incomplete

TRENDS: Incomplete

def parse_chart_song(data): ...
def parse_chart_artist(data): ...
def parse_chart_trending(data): ...
def parse_ranking(data): ...
