from .songs import *
from ._utils import *
from _typeshed import Incomplete

def get_search_result_type(result_type_local, result_types_local): ...
def parse_top_result(data, search_result_types): ...
def parse_search_result(data, search_result_types, result_type, category): ...
def parse_search_results(results, search_result_types, resultType: Incomplete | None = ..., category: Incomplete | None = ...): ...
def get_search_params(filter, scope, ignore_spelling): ...
def parse_search_suggestions(results, detailed_runs): ...
