from ._utils import *

def parse_song_artists(data, index): ...
def parse_song_artists_runs(runs): ...
def parse_song_runs(runs): ...
def parse_song_album(data, index): ...
def parse_song_menu_tokens(item): ...
def parse_like_status(service): ...
