from ytmusicapi.parsers.browsing import *
from ._utils import get_datestamp as get_datestamp
from typing import Dict, List
from ytmusicapi.continuations import get_continuations as get_continuations
from ytmusicapi.helpers import YTM_DOMAIN as YTM_DOMAIN, sum_total_duration as sum_total_duration
from ytmusicapi.parsers.albums import parse_album_header as parse_album_header
from ytmusicapi.parsers.library import parse_albums as parse_albums
from ytmusicapi.parsers.playlists import parse_playlist_items as parse_playlist_items

class BrowsingMixin:
    def get_home(self, limit: int = ...) -> List[Dict]: ...
    def get_artist(self, channelId: str) -> Dict: ...
    def get_artist_albums(self, channelId: str, params: str) -> List[Dict]: ...
    def get_user(self, channelId: str) -> Dict: ...
    def get_user_playlists(self, channelId: str, params: str) -> List[Dict]: ...
    def get_album_browse_id(self, audioPlaylistId: str) -> str: ...
    def get_album(self, browseId: str) -> Dict: ...
    def get_song(self, videoId: str, signatureTimestamp: int = ...) -> Dict: ...
    def get_song_related(self, browseId: str): ...
    def get_lyrics(self, browseId: str) -> Dict: ...
    def get_basejs_url(self): ...
    def get_signatureTimestamp(self, url: str = ...) -> int: ...
    def get_tasteprofile(self) -> Dict: ...
    def set_tasteprofile(self, artists: List[str], taste_profile: Dict = ...) -> None: ...
