from ytmusicapi.parsers.explore import *
from typing import Dict, List

class ExploreMixin:
    def get_mood_categories(self) -> Dict: ...
    def get_mood_playlists(self, params: str) -> List[Dict]: ...
    def get_charts(self, country: str = ...) -> Dict: ...
