import requests
from requests.structures import CaseInsensitiveDict as CaseInsensitiveDict
from typing import Dict, Optional
from ytmusicapi.constants import OAUTH_CLIENT_ID as OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET as OAUTH_CLIENT_SECRET, OAUTH_CODE_URL as OAUTH_CODE_URL, OAUTH_SCOPE as OAUTH_SCOPE, OAUTH_TOKEN_URL as OAUTH_TOKEN_URL, OAUTH_USER_AGENT as OAUTH_USER_AGENT
from ytmusicapi.helpers import initialize_headers as initialize_headers

def is_oauth(headers: CaseInsensitiveDict) -> bool: ...
def is_custom_oauth(headers: CaseInsensitiveDict) -> bool: ...

class YTMusicOAuth:
    def __init__(self, session: requests.Session, proxies: Dict = ...) -> None: ...
    def get_code(self) -> Dict: ...
    def get_token_from_code(self, device_code: str) -> Dict: ...
    def refresh_token(self, refresh_token: str) -> Dict: ...
    @staticmethod
    def dump_token(token: Dict, filepath: Optional[str]): ...
    def setup(self, filepath: Optional[str] = ..., open_browser: bool = ...) -> Dict: ...
    def load_headers(self, token: Dict, filepath: Optional[str] = ...): ...
